// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4e36c0365ad90e62 "portfolio NEW", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'desktop' | 'laptop' | 'tablet' | 'mobile' // Variant
 * background?: string // Background
 * textColor?: string // Text Color
 * title?: string // Title
 * role?: string // role
 * projet?: string // projet
 * amount?: string // Amount
 * link?: string // Link
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * padding?: undefined // Padding
 * stack?: string // stack
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-64SSKMCJ.js";
import { Icon } from "./chunks/chunk-KD6F3UC3.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-VSZVTDLT.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-AZCZYYGU.js";

// virtual:card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ePQCFWfIGkhQqhqYBiG8/bjxgnnFQmZCBw6r5HYcy/RLVvXwAJk.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MaterialFonts = getFonts(Icon);
var enabledGestures = {
	HPcRQBqXS: {
		hover: true,
	},
	je0pCjEnj: {
		hover: true,
	},
	l5wzKxMJN: {
		hover: true,
	},
	X92J8tc0t: {
		hover: true,
	},
};
var cycleOrder = ["HPcRQBqXS", "l5wzKxMJN", "je0pCjEnj", "X92J8tc0t"];
var serializationHash = "framer-PDZG6";
var variantClassNames = {
	HPcRQBqXS: "framer-v-8j9ozu",
	je0pCjEnj: "framer-v-1sprajt",
	l5wzKxMJN: "framer-v-jbzu2s",
	X92J8tc0t: "framer-v-9brd9o",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var numberToPixelString = (value) => {
	if (typeof value !== "number") return value;
	if (!Number.isFinite(value)) return void 0;
	return Math.max(0, value) + "px";
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	desktop: "HPcRQBqXS",
	laptop: "l5wzKxMJN",
	mobile: "X92J8tc0t",
	tablet: "je0pCjEnj",
};
var getProps = ({
	amount,
	background,
	height,
	id,
	image,
	link,
	padding,
	projet,
	role,
	stack,
	textColor,
	title,
	width,
	...props
}) => {
	return {
		...props,
		avVKDWRIG: role ?? props.avVKDWRIG ?? "Description",
		enyQTFGl5: background ?? props.enyQTFGl5 ?? "rgb(238, 255, 0)",
		HNdJyx_ZD: link ?? props.HNdJyx_ZD,
		jQPFv_4xA: padding ?? props.jQPFv_4xA ?? "0px",
		lSB3XNzQs: projet ?? props.lSB3XNzQs ?? "Branding and identity",
		MUlgyJEIg: textColor ?? props.MUlgyJEIg ?? "rgb(0, 0, 0)",
		N2NdkcDAy: image ?? props.N2NdkcDAy,
		POe5RX9yr: amount ?? props.POe5RX9yr ?? "2023",
		v4nQNdbNw: title ?? props.v4nQNdbNw ?? "Project Name",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "HPcRQBqXS",
		W0Rf3F34c: stack ?? props.W0Rf3F34c ?? "WeWeb, automatisations",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		enyQTFGl5: enyQTFGl52,
		MUlgyJEIg: MUlgyJEIg2,
		v4nQNdbNw: v4nQNdbNw2,
		avVKDWRIG: avVKDWRIG2,
		lSB3XNzQs: lSB3XNzQs2,
		POe5RX9yr: POe5RX9yr2,
		HNdJyx_ZD: HNdJyx_ZD2,
		N2NdkcDAy: N2NdkcDAy2,
		jQPFv_4xA: jQPFv_4xA2,
		W0Rf3F34c: W0Rf3F34c2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "HPcRQBqXS",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={HNdJyx_ZD2}
						motionChild={true}
						nodeId={"HPcRQBqXS"}
						scopeId={"RLVvXwAJk"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-8j9ozu", className3, classNames)} framer-m3fnl7`}
							data-framer-name={"desktop"}
							layoutDependency={layoutDependency}
							layoutId={"HPcRQBqXS"}
							ref={refBinding}
							style={{
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
								...style,
							}}
							{...addPropertyOverrides(
								{
									"HPcRQBqXS-hover": {
										"data-framer-name": void 0,
									},
									"je0pCjEnj-hover": {
										"data-framer-name": void 0,
									},
									"l5wzKxMJN-hover": {
										"data-framer-name": void 0,
									},
									"X92J8tc0t-hover": {
										"data-framer-name": void 0,
									},
									je0pCjEnj: {
										"data-framer-name": "tablet",
									},
									l5wzKxMJN: {
										"data-framer-name": "laptop",
									},
									X92J8tc0t: {
										"data-framer-name": "mobile",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-15a9kgh"}
								data-framer-name={"Top Container"}
								layoutDependency={layoutDependency}
								layoutId={"N4qxu8PtM"}
								style={{
									"--1uynrcx": numberToPixelString(jQPFv_4xA2),
								}}
							>
								<motion.div
									className={"framer-17e0mi7"}
									layoutDependency={layoutDependency}
									layoutId={"Ii9rGjAxh"}
								/>
							</motion.div>
							<Transition value={transition1}>
								<motion.div
									className={"framer-1yttaha"}
									data-border={true}
									data-framer-name={"Top Content"}
									layoutDependency={layoutDependency}
									layoutId={"o57sYMlUJ"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-9b54e130-a21e-4df7-b158-707338e41ccb, rgba(255, 255, 255, 0.1))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backgroundColor: enyQTFGl52,
										borderBottomLeftRadius: 8,
										borderBottomRightRadius: 8,
										borderTopLeftRadius: 8,
										borderTopRightRadius: 8,
										boxShadow: "0px -48px 66px 0px rgba(0, 0, 0, 0.25)",
									}}
								>
									<motion.div
										className={"framer-6l404j"}
										data-framer-name={"Tagline"}
										layoutDependency={layoutDependency}
										layoutId={"i83f6CwxL"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-119xef0"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"gMpMJQnqI"}
											style={{
												"--extracted-r6o4lv":
													"var(--variable-reference-MUlgyJEIg-RLVvXwAJk)",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
												"--variable-reference-MUlgyJEIg-RLVvXwAJk": MUlgyJEIg2,
											}}
											text={POe5RX9yr2}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1i4mbrj"}
													data-styles-preset={"s0y5Rymtd"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--variable-reference-MUlgyJEIg-RLVvXwAJk))",
													}}
												>
													{"2023"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-18rykv0"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"Bx16zvyfn"}
											style={{
												"--extracted-r6o4lv":
													"var(--variable-reference-MUlgyJEIg-RLVvXwAJk)",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
												"--variable-reference-MUlgyJEIg-RLVvXwAJk": MUlgyJEIg2,
											}}
											text={lSB3XNzQs2}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1i4mbrj"}
													data-styles-preset={"s0y5Rymtd"}
													style={{
														"--framer-text-alignment": "right",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--variable-reference-MUlgyJEIg-RLVvXwAJk))",
													}}
												>
													{"Branding and identity"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
									<motion.div
										className={"framer-1i63led"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"STatZamF4"}
										style={{
											backgroundColor: MUlgyJEIg2,
											opacity: 0.25,
										}}
									/>
									<motion.div
										className={"framer-1t30k80"}
										data-framer-name={"Heading"}
										layoutDependency={layoutDependency}
										layoutId={"pM38aVsQ3"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-89bjjn"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"nDRY9qHf7"}
											style={{
												"--extracted-1of0zx5":
													"var(--variable-reference-MUlgyJEIg-RLVvXwAJk)",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
												"--variable-reference-MUlgyJEIg-RLVvXwAJk": MUlgyJEIg2,
											}}
											text={v4nQNdbNw2}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h2
													className={"framer-styles-preset-1wml6uu"}
													data-styles-preset={"fVxnimdqP"}
													style={{
														"--framer-text-color":
															"var(--extracted-1of0zx5, var(--variable-reference-MUlgyJEIg-RLVvXwAJk))",
													}}
												>
													{"Project Name"}
												</motion.h2>
											</React.Fragment>
										</RichText>
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-e2k335-container"}
												isAuthoredByUser={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"ux7iW2ZVC-container"}
												nodeId={"ux7iW2ZVC"}
												rendersWithMotion={true}
												scopeId={"RLVvXwAJk"}
												style={{
													rotate: 0,
												}}
												variants={{
													"HPcRQBqXS-hover": {
														rotate: -45,
													},
													"je0pCjEnj-hover": {
														rotate: -45,
													},
													"l5wzKxMJN-hover": {
														rotate: -45,
													},
													"X92J8tc0t-hover": {
														rotate: -45,
													},
												}}
											>
												<Icon
													color={MUlgyJEIg2}
													height={"100%"}
													iconSearch={"Home"}
													iconSelection={"ArrowForward"}
													iconStyle15={"Filled"}
													iconStyle2={"Filled"}
													iconStyle7={"Filled"}
													id={"ux7iW2ZVC"}
													layoutId={"ux7iW2ZVC"}
													mirrored={false}
													selectByList={true}
													style={{
														height: "100%",
														width: "100%",
													}}
													width={"100%"}
												/>
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion.div>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1xz5jhv"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"CzuSRc9UN"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-cd708a3c-25bb-4606-92f4-351c74f13945, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={avVKDWRIG2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1i4mbrj"}
												data-styles-preset={"s0y5Rymtd"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-cd708a3c-25bb-4606-92f4-351c74f13945, rgb(0, 0, 0)))",
												}}
											>
												{"Front-end & back-end "}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-x501fi"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"C8Ml4CSNV"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-cd708a3c-25bb-4606-92f4-351c74f13945, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={W0Rf3F34c2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1i4mbrj"}
												data-styles-preset={"s0y5Rymtd"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-cd708a3c-25bb-4606-92f4-351c74f13945, rgb(0, 0, 0)))",
												}}
											>
												{"Front-end & back-end "}
											</motion.p>
										</React.Fragment>
									</RichText>
									<Image
										background={{
											alt: "",
											fit: "fill",
											sizes: `calc(${componentViewport?.width || "100vw"} - 48px)`,
											...toResponsiveImage(N2NdkcDAy2),
										}}
										className={"framer-1bprxr"}
										layoutDependency={layoutDependency}
										layoutId={"Ye6Ts0OT5"}
										{...addPropertyOverrides(
											{
												je0pCjEnj: {
													background: {
														alt: "",
														fit: "fill",
														sizes: `calc(${componentViewport?.width || "100vw"} - 80px)`,
														...toResponsiveImage(N2NdkcDAy2),
													},
												},
												l5wzKxMJN: {
													background: {
														alt: "",
														fit: "fill",
														sizes: `calc(${componentViewport?.width || "100vw"} - 88px)`,
														...toResponsiveImage(N2NdkcDAy2),
													},
												},
												X92J8tc0t: {
													background: {
														alt: "",
														fit: "fit",
														sizes: `calc(${componentViewport?.width || "100vw"} - 64px)`,
														...toResponsiveImage(N2NdkcDAy2),
														...{
															positionX: "center",
															positionY: "center",
														},
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
							</Transition>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PDZG6.framer-m3fnl7, .framer-PDZG6 .framer-m3fnl7 { display: block; }",
	".framer-PDZG6.framer-8j9ozu { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 680px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 836px; }",
	".framer-PDZG6 .framer-15a9kgh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: var(--1uynrcx); position: relative; width: 100%; }",
	".framer-PDZG6 .framer-17e0mi7 { flex: 1 0 0px; height: 1px; overflow: visible; position: relative; width: 1px; }",
	".framer-PDZG6 .framer-1yttaha { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: 1px; justify-content: flex-start; overflow: hidden; padding: 24px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-PDZG6 .framer-6l404j { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-PDZG6 .framer-119xef0 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-PDZG6 .framer-18rykv0, .framer-PDZG6 .framer-89bjjn { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-PDZG6 .framer-1i63led { flex: none; height: 1px; overflow: visible; position: relative; width: 100%; }",
	".framer-PDZG6 .framer-1t30k80 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PDZG6 .framer-e2k335-container { flex: none; height: 72px; position: relative; width: 72px; }",
	".framer-PDZG6 .framer-1xz5jhv, .framer-PDZG6 .framer-x501fi { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 787px; word-break: break-word; word-wrap: break-word; }",
	".framer-PDZG6 .framer-1bprxr { flex: 1 0 0px; height: 1px; overflow: visible; position: relative; width: 100%; }",
	".framer-PDZG6.framer-v-jbzu2s.framer-8j9ozu { padding: 20px; width: 989px; }",
	".framer-PDZG6.framer-v-jbzu2s .framer-e2k335-container { height: 48px; width: 48px; }",
	".framer-PDZG6.framer-v-1sprajt.framer-8j9ozu { padding: 16px; width: 810px; }",
	".framer-PDZG6.framer-v-1sprajt .framer-e2k335-container { height: 36px; width: 36px; }",
	".framer-PDZG6.framer-v-9brd9o.framer-8j9ozu { gap: 8px; height: 479px; padding: 8px; width: 368px; }",
	".framer-PDZG6.framer-v-9brd9o .framer-6l404j { align-content: flex-start; align-items: flex-start; }",
	".framer-PDZG6.framer-v-9brd9o .framer-e2k335-container { height: 32px; width: 32px; }",
	".framer-PDZG6.framer-v-9brd9o .framer-1xz5jhv { width: 314px; }",
	...css2,
	...css,
	'.framer-PDZG6[data-border="true"]::after, .framer-PDZG6 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerRLVvXwAJk = withCSS(Component, css3, "framer-PDZG6");
var stdin_default = FramerRLVvXwAJk;
FramerRLVvXwAJk.displayName = "Card";
FramerRLVvXwAJk.defaultProps = {
	height: 680,
	width: 836,
};
addPropertyControls(FramerRLVvXwAJk, {
	variant: {
		options: ["HPcRQBqXS", "l5wzKxMJN", "je0pCjEnj", "X92J8tc0t"],
		optionTitles: ["desktop", "laptop", "tablet", "mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	enyQTFGl5: {
		defaultValue: "rgb(238, 255, 0)",
		title: "Background",
		type: ControlType.Color,
	},
	MUlgyJEIg: {
		defaultValue: "rgb(0, 0, 0)",
		title: "Text Color",
		type: ControlType.Color,
	},
	v4nQNdbNw: {
		defaultValue: "Project Name",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	avVKDWRIG: {
		defaultValue: "Description",
		description: "",
		placeholder: "Description",
		title: "role",
		type: ControlType.String,
	},
	lSB3XNzQs: {
		defaultValue: "Branding and identity",
		displayTextArea: false,
		title: "projet",
		type: ControlType.String,
	},
	POe5RX9yr: {
		defaultValue: "2023",
		displayTextArea: false,
		title: "Amount",
		type: ControlType.String,
	},
	HNdJyx_ZD: {
		title: "Link",
		type: ControlType.Link,
	},
	N2NdkcDAy: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	jQPFv_4xA: {
		defaultValue: "0px",
		title: "Padding",
		type: ControlType.Padding,
	},
	W0Rf3F34c: {
		defaultValue: "WeWeb, automatisations",
		description: "stack",
		displayTextArea: false,
		placeholder: "WeWeb, automatisations",
		title: "stack",
		type: ControlType.String,
	},
});
addFonts(
	FramerRLVvXwAJk,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...MaterialFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "X92J8tc0t",
	md: "je0pCjEnj",
	lg: "l5wzKxMJN",
	xl: "HPcRQBqXS",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4e36c0365ad90e622a038006b6d0841ae133cba3ea51a1d4bd0596268aac1390"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4e36c0365ad90e622a038006b6d0841ae133cba3ea51a1d4bd0596268aac1390"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var card_default = ComponentWithRoot;
export { card_default as default };
