// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 4e36c0365ad90e62 "portfolio NEW", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'desktop' | 'mobile' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-KKM5WWDN.js";
import "./chunks/chunk-OQ7T4UMT.js";
import "./chunks/chunk-FFKKJX6Q.js";
import { className, css, fonts } from "./chunks/chunk-64SSKMCJ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-VSZVTDLT.js";
import "./chunks/chunk-HR56UER2.js";
import { routes } from "./chunks/chunk-AZCZYYGU.js";

// virtual:cta
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/2DL8pIn6h2hxRfQsqaum/ZjTqj0wwLFSMZ2zebiLr/CU3xNJ7B8.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var SocialFonts = getFonts(stdin_default);
var cycleOrder = ["xV7AUf3kU", "QixkkqWov"];
var serializationHash = "framer-HkuA0";
var variantClassNames = {
	QixkkqWov: "framer-v-maw0dh",
	xV7AUf3kU: "framer-v-syn3b5",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	desktop: "xV7AUf3kU",
	mobile: "QixkkqWov",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "xV7AUf3kU",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "xV7AUf3kU",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-syn3b5",
							className3,
							classNames,
						)}
						data-framer-name={"desktop"}
						layoutDependency={layoutDependency}
						layoutId={"xV7AUf3kU"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								QixkkqWov: {
									"data-framer-name": "mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-gkfvri"}
							data-framer-name={"Tagline"}
							layoutDependency={layoutDependency}
							layoutId={"ov4NZOvcb"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-13mqwj5"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"q2PVOWo6S"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1i4mbrj"}
										data-styles-preset={"s0y5Rymtd"}
									>
										{".contact"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-t4ju05"}
								layoutDependency={layoutDependency}
								layoutId={"S088OL9VD"}
								style={{
									backgroundColor:
										"var(--token-a340cc26-67d8-46d6-a7d5-1c24a414cd4c, rgba(255, 255, 255, 0.25))",
								}}
							/>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1ijc0sv"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"bkXMX9OxQ"}
							style={{
								"--extracted-1of0zx5":
									"var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h2
									className={"framer-styles-preset-1wml6uu"}
									data-styles-preset={"fVxnimdqP"}
									style={{
										"--framer-text-color":
											"var(--extracted-1of0zx5, var(--token-86117d10-82c0-48ca-83b9-ad514639102d, rgb(255, 255, 255)))",
									}}
								>
									{"Parlez-moi de votre projet!"}
								</motion.h2>
							</React.Fragment>
						</RichText>
						<motion.div
							className={"framer-1ovod37"}
							data-framer-name={"Social Items"}
							layoutDependency={layoutDependency}
							layoutId={"n8k1OGJMe"}
						>
							<ComponentViewportProvider
								height={60}
								width={`max((${componentViewport?.width || "100vw"} - 96px) / 3, 1px)`}
								y={(componentViewport?.y || 0) + 0 + 266 + 13.5}
								{...addPropertyOverrides(
									{
										QixkkqWov: {
											width: componentViewport?.width || "100vw",
											y: (componentViewport?.y || 0) + 0 + 202 + 0 + 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-ufdcfs-container"}
									layoutDependency={layoutDependency}
									layoutId={"AXoCDuB6x-container"}
									nodeId={"AXoCDuB6x"}
									rendersWithMotion={true}
									scopeId={"CU3xNJ7B8"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "AXoCDuB6x",
										layoutId: "AXoCDuB6x",
										rUZOOFGkG: "linkedin",
										sGYpQw0v8: "LinkedinLogo",
										style: {
											width: "100%",
										},
										variant: "OsQK2HUoa",
										vDe5VE34_: "@antoinecoudert",
										width: "100%",
										xsjiBD9st: "https://www.linkedin.com/in/a-coudert",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={60}
								width={`max((${componentViewport?.width || "100vw"} - 96px) / 3, 1px)`}
								y={(componentViewport?.y || 0) + 0 + 266 + 13.5}
								{...addPropertyOverrides(
									{
										QixkkqWov: {
											width: componentViewport?.width || "100vw",
											y: (componentViewport?.y || 0) + 0 + 202 + 0 + 108,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-islk79-container"}
									layoutDependency={layoutDependency}
									layoutId={"zqo0yRpCL-container"}
									nodeId={"zqo0yRpCL"}
									rendersWithMotion={true}
									scopeId={"CU3xNJ7B8"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "zqo0yRpCL",
										layoutId: "zqo0yRpCL",
										rUZOOFGkG: "email",
										sGYpQw0v8: "Mailbox",
										style: {
											width: "100%",
										},
										variant: "OsQK2HUoa",
										vDe5VE34_: "antoine@coudert.io",
										width: "100%",
										xsjiBD9st: "mailto:antoine@coudert.io",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={60}
								width={`max((${componentViewport?.width || "100vw"} - 96px) / 3, 1px)`}
								y={(componentViewport?.y || 0) + 0 + 266 + 13.5}
								{...addPropertyOverrides(
									{
										QixkkqWov: {
											width: componentViewport?.width || "100vw",
											y: (componentViewport?.y || 0) + 0 + 202 + 0 + 216,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-15ahy0l-container"}
									layoutDependency={layoutDependency}
									layoutId={"oO_r6_fEd-container"}
									nodeId={"oO_r6_fEd"}
									rendersWithMotion={true}
									scopeId={"CU3xNJ7B8"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "oO_r6_fEd",
										layoutId: "oO_r6_fEd",
										rUZOOFGkG: "cal",
										sGYpQw0v8: "Calendar",
										style: {
											width: "100%",
										},
										variant: "OsQK2HUoa",
										vDe5VE34_: "@antoine",
										width: "100%",
										xsjiBD9st: "https://cal.com/antoine-coudert/30min",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-HkuA0.framer-1v1i1d0, .framer-HkuA0 .framer-1v1i1d0 { display: block; }",
	".framer-HkuA0.framer-syn3b5 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
	".framer-HkuA0 .framer-gkfvri { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-HkuA0 .framer-13mqwj5 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-HkuA0 .framer-t4ju05 { flex: 1 0 0px; height: 1px; overflow: hidden; position: relative; width: 1px; }",
	".framer-HkuA0 .framer-1ijc0sv { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 75%; word-break: break-word; word-wrap: break-word; }",
	".framer-HkuA0 .framer-1ovod37 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: 87px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-HkuA0 .framer-ufdcfs-container, .framer-HkuA0 .framer-islk79-container, .framer-HkuA0 .framer-15ahy0l-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-HkuA0.framer-v-maw0dh.framer-syn3b5 { gap: 48px; }",
	".framer-HkuA0.framer-v-maw0dh .framer-1ovod37 { flex-direction: column; height: 398px; }",
	".framer-HkuA0.framer-v-maw0dh .framer-ufdcfs-container, .framer-HkuA0.framer-v-maw0dh .framer-islk79-container, .framer-HkuA0.framer-v-maw0dh .framer-15ahy0l-container { flex: none; width: 100%; }",
	...css2,
	...css,
];
var FramerCU3xNJ7B8 = withCSS(Component, css3, "framer-HkuA0");
var stdin_default2 = FramerCU3xNJ7B8;
FramerCU3xNJ7B8.displayName = "CTA";
FramerCU3xNJ7B8.defaultProps = {
	height: 353,
	width: 1200,
};
addPropertyControls(FramerCU3xNJ7B8, {
	variant: {
		options: ["xV7AUf3kU", "QixkkqWov"],
		optionTitles: ["desktop", "mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerCU3xNJ7B8,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SocialFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cta
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "QixkkqWov",
	xl: "xV7AUf3kU",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4e36c0365ad90e622a038006b6d0841ae133cba3ea51a1d4bd0596268aac1390"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"4e36c0365ad90e622a038006b6d0841ae133cba3ea51a1d4bd0596268aac1390"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var cta_default = ComponentWithRoot;
export { cta_default as default };
